### ISSUE TITLE
add html resources

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/web-development-Resource#1]

**Comment by codewithvk** [comment]
can you assign me? I would like to happy to work on this issue.

**Comment by Surajbokde** [comment]
@codewithvk thanks for showing interest .
did u join my slack channel ?
are you contributing under KWOC2020??

**Comment by codewithvk** [comment]
@Surajbokde Yes

**Comment by Surajbokde** [comment]
@codewithvk make a Html folder and start adding resources under that.
make PR after 6th Dec

**Comment by codewithvk** [comment]
sure @Surajbokde !! Thanks for assigned me.

**Comment by codewithvk** [comment]
Can you close this isse?

**Comment by has12zen** [comment]
Hi, I would also like to contribute can you assign any task.

**Comment by Surajbokde** [comment]
@has12zen i will assign this issue to you atart working on this issue
