### ISSUE TITLE
nodejs resources

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/web-development-Resource#10]

**Comment by has12zen** [comment]
Hi I would Like to work on this issue can  you assign it to me

**Comment by codewithvk** [comment]
I want to work on this issue.

**Comment by Surajbokde** [comment]
@codewithvk  start your work

**Comment by ghost** [comment]
@Surajbokde Sir, I want to work on this issue and add some awesome resources to it. Please assign this issue to me.

**Comment by Ayushgup85** [comment]
Can you please assign this issue to me?

**Comment by ghost** [comment]
Can you please assign this issue to me?
