### ISSUE TITLE
vuejs resources

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/web-development-Resource#11]

**Comment by AmanSingh0-0** [comment]
Assign to me

**Comment by Surajbokde** [comment]
@AmanSingh0-0 start your work

**Comment by ineffable23** [comment]
@Surajbokde I'd like to work on this issue if it's still available.

**Comment by yashasvimisra2798** [comment]
@Surajbokde please assign this issue to me, I want to work on this.
