### ISSUE TITLE
Django resources

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/web-development-Resource#12]

**Comment by anushkasinghal11** [comment]
Can I take this up?

**Comment by Surajbokde** [comment]
@anushkasinghal11 start your work but remember  use `git pull https://github.com/Surajbokde/web-development-Resource.git` before starting ur work and before pushing your code

**Comment by Nivedita967** [comment]
Hey, Can I add some more resources?

**Comment by Poobalan1210** [comment]
hey, can you assign me this issue to add some more to it?

**Comment by Surajbokde** [comment]
@Nivedita967 go ahead

**Comment by ghost** [comment]
hey, can you assign me this issue to add some more to it?

**Comment by Surajbokde** [comment]
@Ak-panchal do it

**Comment by ineffable23** [comment]
@Surajbokde I'd like to work on this issue if it's still available
