### ISSUE TITLE
NuxtJS resources

### ISSUE THREAD

**Issue by Aarushi11H** [Surajbokde/web-development-Resource#159]
A Javascript framework.

**Comment by Surajbokde** [comment]
@Aarushi11H  do it in js framework folder

**Comment by yashasvimisra2798** [comment]
Can I work on this issue?

**Comment by ghost** [comment]
Can I work on this issue?

**Comment by Surajbokde** [comment]
@Ak-panchal go ahead

**Comment by yashasvimisra2798** [comment]
@Surajbokde can I work on this?
