### ISSUE TITLE
add css resources

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/web-development-Resource#2]

**Comment by codewithvk** [comment]
can you assign me? I would like to happy to work on this issue.

**Comment by codewithvk** [comment]
@Surajbokde

**Comment by anushkasinghal11** [comment]
Hey!
Can I add more resources to this?

**Comment by Shagufta08** [comment]
Hi!
Can you assign this to me?
I would like to work on this issue.

**Comment by RamniwasMahala007** [comment]
Hello @Surajbokde 
Can you assign this to me?
I would like to work on this issue.

**Comment by Surajbokde** [comment]
@RamniwasMahala007 i am assigning this issue to u .
introduce yourself on slack channel

**Comment by ghost** [comment]
@Surajbokde Sir I want to work on this issue. Please assign it to me. I have already joined slack workspace and introduced me there.

**Comment by Surajbokde** [comment]
@urvashi-code1255 go ahead
