### ISSUE TITLE
add react.js resources

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/web-development-Resource#3]

**Comment by codewithvk** [comment]
can you assign me? I would like to happy to work on this issue.

**Comment by codewithvk** [comment]
@Surajbokde

**Comment by anushkasinghal11** [comment]
Hello! Can you assign this to me?

**Comment by Surajbokde** [comment]
@anushkasinghal11 did you join slack workspace ?? and introduce yourself?

**Comment by Surajbokde** [comment]
@codewithvk first complete css resource

**Comment by anushkasinghal11** [comment]
Yes!

**Comment by Surajbokde** [comment]
@codewithvk  start your work

**Comment by ever-cell** [comment]
@Surajbokde I want to add more resources. Please assign me

**Comment by Surajbokde** [comment]
@ShreyaDhir go ahead
