### ISSUE TITLE
MongoDB resource

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/web-development-Resource#38]

**Comment by anushkasinghal11** [comment]
Hey!
I would like to work on this.

**Comment by codewithvk** [comment]
@Surajbokde Can you assign me?

**Comment by Surajbokde** [comment]
@codewithvk do it

**Comment by ghost** [comment]
@Surajbokde Sir, I want to work on this issue. Please assign it to me.

**Comment by Ayushgup85** [comment]
Can i work on this issue?

**Comment by Surajbokde** [comment]
@Ayushgup85 go ahead

**Comment by ghost** [comment]
Can I work on this issue?

**Comment by ineffable23** [comment]
@Surajbokde I'd like to work on this issue if it's still available

**Comment by Raviruler** [comment]
_Hey @Surajbokde , Can you please assign me this . I like to work on this issue._

**Comment by kitarp29** [comment]
hey @Surajbokde  can add a PR with this issue??

**Comment by Surajbokde** [comment]
@kitarp29  do it
