### ISSUE TITLE
Add php resources

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/web-development-Resource#4]
make a folder and add php resources

**Comment by rajghosh2000** [comment]
Can I add some documentation to it.

**Comment by Surajbokde** [comment]
@rajghosh2000  did u register yourself under kwoc2020?

**Comment by rajghosh2000** [comment]
Yes I have

**Comment by Surajbokde** [comment]
@rajghosh2000  introduce yourself on introduction channel.

i will assign you this issue make a folder the add resources to it. 
make PR after 7th dec.

**Comment by rajghosh2000** [comment]
Ok

**Comment by rajghosh2000** [comment]
Can I start with this from today and will make the pull request after 7th as you mentioned.

**Comment by Surajbokde** [comment]
@rajghosh2000 i don't know the exact date from where the organizer of kwoc will see yours work.

**Comment by Surajbokde** [comment]
@rajghosh2000  make pr as soon as possible

**Comment by rajghosh2000** [comment]
Ok I will by today evening may be . Will this be ok ?

**Comment by rajghosh2000** [comment]
I will create a folder containing 3 files mainly 1 for beginners , 1 for intermediates and 1 for advanced part . For today I will create the beginners one and do the pr . Will this be ok for today ?

**Comment by Surajbokde** [comment]
@rajghosh2000 add all resources in readme file of that php folder( create folder if it is not there) and when you add all resources then make PR.
If u r facing any difficulty then ask me on slack .

**Comment by Surajbokde** [comment]
@rajghosh2000  u did nice work in your first PR. 
waiting for intermediate and advance part (try to do it as early as possible).

**Comment by rajghosh2000** [comment]
Will do the pr by tomorrow. Sorry for the delay.

**Comment by ineffable23** [comment]
@Surajbokde I'd like to work on this issue if it's still available

**Comment by Surajbokde** [comment]
@ineffable23  do it if u wants to add the resources . and before that first complete the assign issue in nature_beauty

**Comment by ineffable23** [comment]
Yup, I'm working on it.
