### ISSUE TITLE
Wanna add some cheat sheets

### ISSUE THREAD

**Issue by hr1shu** [Surajbokde/web-development-Resource#48]
Cheat sheets are a quick guide and you can always take a peek and remember back everything. I have a few cheat sheets related to web development.
Allow me to proceed further, Thanks.

**Comment by Surajbokde** [comment]
@hr1shu are u adding your own cheat-sheet?

**Comment by hr1shu** [comment]
I have collected them from different sources.
my own collection Specifically for web dev

**Comment by Surajbokde** [comment]
@hr1shu do add that in there respective folder

**Comment by hr1shu** [comment]
Sure
