### ISSUE TITLE
Add javascript resource

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/web-development-Resource#5]
make a folder of javascript and then add resources in that

**Comment by prit108** [comment]
@Surajbokde I would like to work on this. I already joined the Slack.

**Comment by Surajbokde** [comment]
@prit108  i will assign you this issue .
if you didn't introduce yourself then do it.

and make a folder then add resources

**Comment by has12zen** [comment]
I have joined the slack workspace and I would like to work on this issue, Can you assign this issue to me?

**Comment by ever-cell** [comment]
@Surajbokde I want to add more resources. Please assign me
