### ISSUE TITLE
Contributes in Readme. Md

### ISSUE THREAD

**Issue by codewithvk** [Surajbokde/web-development-Resource#56]
Can you assign me?

**Comment by Surajbokde** [comment]
@codewithvk  plz explain what u wants to do

**Comment by codewithvk** [comment]
![Capture](https://user-images.githubusercontent.com/61119120/101894072-a22a1980-3bcb-11eb-9ee7-422a3fe990b6.PNG)
You can see

**Comment by Surajbokde** [comment]
ok do add contributors in readme.md
