### ISSUE TITLE
web-design issue 

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/web-development-Resource#6]

**Comment by has12zen** [comment]
Hi, I know a bit of Js and would like to contribute can you tell me how to get started, and can you assign me an issue.

**Comment by Surajbokde** [comment]
@has12zen did you join slack workspace ? if not then join and introduce yourself first.

**Comment by ineffable23** [comment]
Hey @Surajbokde  I'm proficient in HTML 5, CSS3, Bootstrap 4.5, Javascript ES6. I'm a UX/UI designer. I'm highly interested to work on this issue, please assign it to me.

**Comment by Surajbokde** [comment]
@ineffable23 i will assign this issue to u .
create a folder of web design (if not created) the add readme.md file and then start your work.

**Comment by ghost** [comment]
@Surajbokde Sir, I want to work on this issue. Please assign it to me.
