### ISSUE TITLE
Svelte Javascript Framework Resources

### ISSUE THREAD

**Issue by ghost** [Surajbokde/web-development-Resource#76]
@Surajbokde Sir, I want to add Svelte.js resources. Please assign this issue to me.

**Comment by ghost** [comment]
I want to add Svelte.js resources. Please assign this issue to me.

**Comment by Surajbokde** [comment]
@Ak-panchal do it.

**Comment by ineffable23** [comment]
@Surajbokde I'd like to work on this issue if it's still available
