### ISSUE TITLE
Angular js resources

### ISSUE THREAD

**Issue by Surajbokde** [Surajbokde/web-development-Resource#9]

**Comment by umar07** [comment]
Hey, would like to contribute to this issue.

**Comment by Surajbokde** [comment]
@umar07 i assigned this issue to u .Start your work

**Comment by umar07** [comment]
Sure!

**Comment by Shagufta08** [comment]
Hey!
I would like to work on this issue.

**Comment by Surajbokde** [comment]
@Shagufta08 i am assigning this issue to u do it fast .
do introduce yourself on slack .
also i assigned one issue to you at nature_beauty complete that also

**Comment by Shagufta08** [comment]
Sure!
I will complete this as soon as possible.
Thank you

**Comment by Nivedita967** [comment]
Hey, can I work on this issue?

**Comment by Surajbokde** [comment]
@Nivedita967 start your work

**Comment by Raviruler** [comment]
I would like to contribute in this issue.
please assign me this.
@Surajbokde
